default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: Taxi4343
  database: clown-dev
  socket: /tmp/mysql.sock

production:
  <<: *default
  username: root
  password: feliXX17???
  database: clown-prod
  socket: /var/run/mysqld/mysqld.sock